import { RecipeGenerationResponseSchema, type RecipeGenerationResponse } from "../shared/recipe";

/** Schema-validated UI fallback while the configured Gemini project has no usable quota. */
export function createFallbackRecipeResponse(): RecipeGenerationResponse {
  return RecipeGenerationResponseSchema.parse({
    recipes: [
      {
        name: "Moroccan Chicken Tagine",
        flavour: "Warm saffron, sweet apricot, olive, and lemon-spiced chicken.",
        total_time: "1 hr 10 min",
        health_headline: "Chicken and chickpeas create a fragrant, filling meal with protein and fibre.",
        health_insights: ["Chicken provides complete protein.", "Chickpeas contribute gut-supporting fibre.", "Warm spices add depth without a heavy sauce."],
        tags: ["High protein", "Gut-friendly", "High iron"],
        score: 94,
        base_servings: 4,
        missing_ingredients: ["Dried apricots", "Green olives", "Preserved lemon"],
        ingredients: [
          { group: "Protein", name: "Chicken thighs", qty: 700, unit: "g" },
          { group: "Protein", name: "Chickpeas", qty: 400, unit: "g can" },
          { group: "Produce", name: "Onion", qty: 1, unit: null },
          { group: "Produce", name: "Carrot", qty: 2, unit: null },
          { group: "Pantry", name: "Ground cumin", qty: 2, unit: "tsp" },
          { group: "Pantry", name: "Chicken stock", qty: 500, unit: "ml" },
          { group: "To buy", name: "Dried apricots", qty: 80, unit: "g" },
          { group: "To buy", name: "Green olives", qty: 80, unit: "g" },
          { group: "To buy", name: "Preserved lemon", qty: 0.5, unit: null },
        ],
        steps: [
          { order: 1, instruction: "Season and brown the chicken in a heavy pot, then transfer it to a plate.", timer_seconds: 480 },
          { order: 2, instruction: "Soften onion and carrot, then stir through cumin for one minute.", timer_seconds: 420 },
          { order: 3, instruction: "Add chicken, chickpeas, stock, apricots, olives, and lemon. Cover and simmer gently.", timer_seconds: 2100 },
          { order: 4, instruction: "Taste, adjust seasoning, and serve warm.", timer_seconds: null },
        ],
      },
      {
        name: "Spanish Chicken and Chickpea",
        flavour: "Smoky paprika chicken with sweet tomato, pepper, and tender chickpeas.",
        total_time: "45 min",
        health_headline: "A protein-forward skillet meal with fibre-rich chickpeas and iron-containing spinach.",
        health_insights: ["Chicken and chickpeas combine animal and plant protein.", "Spinach contributes iron alongside vitamin-C-rich tomato.", "Smoked paprika delivers depth without excess oil."],
        tags: ["High protein", "Gut-friendly", "High iron", "Low fat"],
        score: 92,
        base_servings: 4,
        missing_ingredients: ["Smoked paprika", "Chicken stock"],
        ingredients: [
          { group: "Protein", name: "Chicken breast", qty: 650, unit: "g" },
          { group: "Protein", name: "Chickpeas", qty: 400, unit: "g can" },
          { group: "Produce", name: "Red bell pepper", qty: 1, unit: null },
          { group: "Produce", name: "Tomatoes", qty: 400, unit: "g" },
          { group: "Produce", name: "Spinach", qty: 120, unit: "g" },
          { group: "Pantry", name: "Olive oil", qty: 1, unit: "tbsp" },
          { group: "To buy", name: "Smoked paprika", qty: 2, unit: "tsp" },
          { group: "To buy", name: "Chicken stock", qty: 250, unit: "ml" },
        ],
        steps: [
          { order: 1, instruction: "Sear seasoned chicken pieces until golden and set aside.", timer_seconds: 420 },
          { order: 2, instruction: "Cook pepper with smoked paprika until fragrant.", timer_seconds: 300 },
          { order: 3, instruction: "Add tomatoes, chickpeas, stock, and chicken. Simmer until thick and cooked through.", timer_seconds: 900 },
          { order: 4, instruction: "Fold in spinach just until wilted.", timer_seconds: 60 },
        ],
      },
      {
        name: "Tuscan Braised Chicken",
        flavour: "Garlic, tomato, rosemary, and cannellini beans in a rustic Tuscan braise.",
        total_time: "1 hr 20 min",
        health_headline: "Chicken and beans make a hearty protein-rich braise with slow-release energy.",
        health_insights: ["Cannellini beans provide satisfying dietary fibre.", "Tomatoes add bright acidity and lycopene.", "Olive oil carries flavour without a cream-based sauce."],
        tags: ["High protein", "Gut-friendly", "Clean carb"],
        score: 89,
        base_servings: 4,
        missing_ingredients: ["Cannellini beans", "Fresh rosemary"],
        ingredients: [
          { group: "Protein", name: "Chicken thighs", qty: 700, unit: "g" },
          { group: "Protein", name: "Cannellini beans", qty: 400, unit: "g can" },
          { group: "Produce", name: "Onion", qty: 1, unit: null },
          { group: "Produce", name: "Cherry tomatoes", qty: 350, unit: "g" },
          { group: "Pantry", name: "Tomato paste", qty: 1, unit: "tbsp" },
          { group: "Pantry", name: "Chicken stock", qty: 400, unit: "ml" },
          { group: "To buy", name: "Cannellini beans", qty: 400, unit: "g can" },
          { group: "To buy", name: "Fresh rosemary", qty: 2, unit: "sprigs" },
        ],
        steps: [
          { order: 1, instruction: "Brown the chicken in a Dutch oven, then set it aside.", timer_seconds: 600 },
          { order: 2, instruction: "Cook onion and tomato paste until aromatic.", timer_seconds: 300 },
          { order: 3, instruction: "Add tomatoes, stock, beans, rosemary, and chicken. Cover and braise gently.", timer_seconds: 2700 },
          { order: 4, instruction: "Rest briefly, then serve the chicken with beans and sauce.", timer_seconds: 300 },
        ],
      },
      {
        name: "Indian Butter Chicken",
        flavour: "Velvety tomato, ginger, and garam masala sauce around tender spiced chicken.",
        total_time: "50 min",
        health_headline: "A comforting high-protein dinner made lighter with yogurt and a measured butter finish.",
        health_insights: ["Chicken makes this a satisfying protein-rich centrepiece.", "Greek yogurt adds creaminess and extra protein.", "Tomato and spices build richness with less added fat."],
        tags: ["High protein", "Indulgent", "Low fat"],
        score: 91,
        base_servings: 4,
        missing_ingredients: ["Garam masala", "Greek yogurt", "Butter"],
        ingredients: [
          { group: "Protein", name: "Chicken breast", qty: 700, unit: "g" },
          { group: "Produce", name: "Onion", qty: 1, unit: null },
          { group: "Produce", name: "Fresh ginger", qty: 25, unit: "g" },
          { group: "Pantry", name: "Crushed tomatoes", qty: 400, unit: "g" },
          { group: "Pantry", name: "Ground cumin", qty: 1, unit: "tsp" },
          { group: "To buy", name: "Garam masala", qty: 2, unit: "tsp" },
          { group: "To buy", name: "Greek yogurt", qty: 180, unit: "g" },
          { group: "To buy", name: "Butter", qty: 20, unit: "g" },
        ],
        steps: [
          { order: 1, instruction: "Season chicken and sear until lightly charred, then set it aside.", timer_seconds: 480 },
          { order: 2, instruction: "Cook onion and ginger, then add tomatoes and spices to make a thick sauce.", timer_seconds: 600 },
          { order: 3, instruction: "Return chicken to the sauce and simmer until cooked through.", timer_seconds: 600 },
          { order: 4, instruction: "Take off the heat, stir in yogurt and butter, then serve.", timer_seconds: null },
        ],
      },
    ],
  });
}
